### PR TITLE
Finding files

### PR DESCRIPTION
**Pull request by lsinh**
@ziad-saab 

Created 2 text files of files containing name "logo" and another one of files over 500kb.

Here's my command line work

lsinh:~/workspace (cmd-history) $ cd ~
lsinh:~ $ pwd
/home/ubuntu
lsinh:~ $ git clone git@github.com:lsinh/decodemtl.git

lsinh:~ $ cd workspace
lsinh:~/workspace (cmd-history) $ history > history.txt

lsinh:~/workspace (cmd-history) $ git add history.txt
lsinh:~/workspace (cmd-history) $ git commit -m "corection: added history.txt after clone of decodemtl repository"

lsinh:~/workspace (cmd-history) $ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.

lsinh:~/workspace (master) $ git checkout -b finding-files
fatal: A branch named 'finding-files' already exists.
lsinh:~/workspace (master) $ git checkout finding-files
Switched to branch 'finding-files'
lsinh:~/workspace (finding-files) $ git status
On branch finding-files
nothing to commit, working directory clean

lsinh:~/workspace (finding-files) $ cd ~
lsinh:~ $ ls
decodemtl/  lib/  workspace/

lsinh:~ $ cd workspace
lsinh:~/workspace (finding-files) $ git checkout finding-files
Already on 'finding-files'

lsinh:~/workspace (finding-files) $ ls
README.md  change.txt  files-over-500kb.txt  files-with-logo.txt  poem.txt

lsinh:~/workspace (finding-files) $ ls ..
decodemtl/  lib/  workspace/

lsinh:~/workspace (finding-files) $ find ../decodemtl -iname '*logo*' > files-with-logo.txt
lsinh:~/workspace (finding-files) $ git add files-with-logo.txt
lsinh:~/workspace (finding-files) $ git commit -m "overwrite files-with-logo.txt"
[finding-files 27d4d77] overwrite files-with-logo.txt
 1 file changed, 2 insertions(+), 2 deletions(-)
lsinh:~/workspace (finding-files) $ find ../decodemtl -size +500k
../decodemtl/src/assets/images/meeting.jpg
../decodemtl/src/assets/images/typewriter.jpg
../decodemtl/.git/objects/pack/pack-0ac076ad7e50300fc8b79032c8118b6d2d3c6078.pack

lsinh:~/workspace (finding-files) $ find ../decodemtl -size +500k > files-over-500kb.txt
lsinh:~/workspace (finding-files) $ git add files-over-500kb.txt
lsinh:~/workspace (finding-files) $ git commit -m "overwrite files-over-500kb.txt"

### CODE REVIEW

**Comment by ziad-saab** [comment]
@lsinh can you please only list the relevant commands to do the exercise, rather than the whole history?

**Comment by lsinh** [comment]
yes, here it is

$ git checkout -b finding-files
$ find ../decodemtl -iname 'logo' > files-with-logo.txt
$ git add files-with-logo.txt
$ git commit -m "overwrite files-with-logo.txt"
$ find ../decodemtl -size +500k > files-over-500kb.txt
$ git add files-over-500kb.txt
$ git commit -m "overwrite files-over-500kb.txt"

**Comment by lsinh** [comment]
$ git origin push finding-files

**Comment by ziad-saab** [comment]
:+1:

**Pull request closed without merging**
