### PR TITLE
Finding files

### PR DESCRIPTION
**Pull request by BabakKhosravifar**

### CODE REVIEW

**Comment by BabakKhosravifar** [comment]
git checkout -b finding-files   
find . -iname "*logo*" > file-with-logo.txt 
git add file-with-logo.txt
git commit -m "file-with-logo committed"
find . +500 > file-over-500kb.txt
git add file-over-500kb.txt
git commit -m "file-over-500kb committed"
git push -u origin finding-files

**Comment by ziad-saab** [comment]
@BabakKhosravifar it seems that your command to find files over 500kb is missing something. You forgot to add `-size`. Please fix and reply to me :)

**Comment by BabakKhosravifar** [comment]
yes I am re-doing the following starting over again:

find ../decodemtl -size +500 > file-over-500kb.txt

**Comment by BabakKhosravifar** [comment]
1  fortune
    2  fortune -a
    3  fortune -e
    4  fortune -e > fortune.txt
    5  fortune tr
    6  man fortune
    7  cat fortune | tr e _ > fortune-replaced.txt
    8  rm fortune-replaced.txt
    9  cat fortune.txt | tr e _ > fortune-replaced.txt
   10  sudo apt-get install cowsay
   11  cowsay
   12  man cowsay
   13  cowsay -e
   14  cowsay fortune
   15  cowsay fortune > cow-fortune.txt
   16  git status
   17  git add cow-fortune.txt
   18  git add fortune-replaced.txt
   19  got add fortune.txt
   20  git status
   21  git add fortune.txt
   22  git status
   23  rm cow-fortune.txt
   24  fortune | cowsay > cow-fortune.txt
   25  git add cow-fortune.txt
   26  git status
   27  git commit -m "cow-said fortune"
   28  git push -u origin finding-files
   29  history

**Comment by BabakKhosravifar** [comment]
1  fortune
    2  fortune -a
    3  fortune -e
    4  fortune -e > fortune.txt
    5  fortune tr
    6  man fortune
    7  cat fortune | tr e _ > fortune-replaced.txt
    8  rm fortune-replaced.txt
    9  cat fortune.txt | tr e _ > fortune-replaced.txt
   10  sudo apt-get install cowsay
   11  cowsay
   12  man cowsay
   13  cowsay -e
   14  cowsay fortune
   15  cowsay fortune > cow-fortune.txt
   16  git status
   17  git add cow-fortune.txt
   18  git add fortune-replaced.txt
   19  got add fortune.txt
   20  git status
   21  git add fortune.txt
   22  git status
   23  rm cow-fortune.txt
   24  fortune | cowsay > cow-fortune.txt
   25  git add cow-fortune.txt
   26  git status
   27  git commit -m "cow-said fortune"
   28  git push -u origin finding-files
   29  history

**Comment by ziad-saab** [comment]
thank you :)

**Pull request closed without merging**
