### PR TITLE
add history.txt

### PR DESCRIPTION
**Pull request by lsinh**
@ Ziad 
Created cmd-history branch and added history.txt

### CODE REVIEW

**Comment by lsinh** [comment]
@ziad-saab 
I added the decodeMTL repository onto cloud9 and overwrote history.txt, also opened the command line in a new terminal

**Comment by ziad-saab** [comment]
@lsinh can you please add a comment here with the command you used to get this output?

**Comment by ziad-saab** [comment]
@lsinh what command did you use to create `history.txt`? this is what i want to know :)

**Comment by lsinh** [comment]
Right sorry, I erased the history but ill recreate it here.

$ cd ~
$ cd workspace
$ git checkout -b cmd-history
$ git history > history.txt
$ git add history.txt
$ git commit -m "corection: added history.txt after clone of decodemtl repository"
$ git push origin cmd-workspace

**Comment by lsinh** [comment]
*cmd-history not cmd-workspace

**Comment by ziad-saab** [comment]
thanks :)

**Pull request closed without merging**
