### PR TITLE
Finding content

### PR DESCRIPTION
**Pull request by alphanumeric0101**
found 'javasctipt' in files, command is in commit message for

### CODE REVIEW

**Comment by ziad-saab** [comment]
@alphanumeric0101 can you please add your commands as a comment to the pull request?

**Comment by alphanumeric0101** [comment]
grep -r -n -l 'javascript' ../workspace/decodemtl > filenames-with-javascript.txt

**Comment by ziad-saab** [comment]
@alphanumeric0101 in this case can you please explain the use of `-n`?

**Comment by alphanumeric0101** [comment]
actually that was my bad.
this was the command I used:

grep -r 'javascript' ../workspace/decodemtl  > files-with-javascript.txt

the command I posted above was for the file files-with-javascript-numers.txt exercise which you did not ask us to commit.

**Comment by ziad-saab** [comment]
thanks!

**Pull request closed without merging**
